/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package eu.dcotta.confis

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe

class LibraryTest: StringSpec({
    "someLibraryMethodReturnsTrue" {
        val classUnderTest = Library()
        classUnderTest.someLibraryMethod() shouldBe true
    }
})
